alias r := rust

_default:
    @just --choose -f {{ justfile() }} -d  {{ invocation_directory() }}

rust:
    @just --choose -f $MY_SCRIPTS/rust.just -d {{ invocation_directory() }}

edit:
    @just --choose -f $MY_SCRIPTS/edit.just -d {{ invocation_directory() }}

cpp-build:
    g++ -ggdb3 -pthread main.cpp

cpp-run:
    ./a.out

cpp-clean:
    /bin/rm -rf a.out

cpp-build-run: cpp-clean cpp-build cpp-run

mise-install-java:
    mise install "java@$(mise ls-remote java | fzf)"

mise-global-java:
    mise use --global "java@$(mise ls-remote java | fzf)"

kakaotalk:
    with-env { LANG: 'ko_KR.UTF-8' } { kakaotalk }

gita-pull:
    git -C ($nu.home-path | path join '.local/share/chezmoi') pull
    git -C ($nu.home-path | path join '.config/nvim') pull
    git -C ($nu.home-path | path join 'my-cubrid') pull

gita-status:
    git -C ($nu.home-path | path join '.local/share/chezmoi') status
    git -C ($nu.home-path | path join '.config/nvim') status
    git -C ($nu.home-path | path join 'my-cubrid') status

vpn:
    sudo openfortivpn cubrid1.fortiddns.com:10443 --username=dhkim@cubrid.com  --trusted-cert fd9fc94cec0b9d3fc5bfdb7c081c4d47083f62a4ff0b3bc7db73b6b13c29fce2

rr-enable:
    echo 1 | sudo tee  /proc/sys/kernel/perf_event_paranoid
    sudo cpupower frequency-set -g performance

cgdb-rust:
    cgdb -d rust-gdb -p (ps -l | where command =~ 'target/debug/.*' | get pid | first)

cgdb-rust-fzf:
    cgdb -d rust-gdb -p (pf)

mdserve:
    mdserve --hostname '0.0.0.0' --port 3000 (fd 'md$' | fzf)

firewall-rocky:
    sudo firewall-cmd --add-port=3000/tcp --permanent
    sudo firewall-cmd --reload
