alias r := rust

_default:
    @just --choose -f {{ justfile() }} -d  {{ invocation_directory() }}

rust:
    @just --choose -f $MY_SCRIPTS/rust.just -d {{ invocation_directory() }}

cpp-build:
    g++ -ggdb3 -pthread main.cpp

cpp-run:
    ./a.out

cpp-clean:
    /bin/rm -rf a.out

cpp-build-run: cpp-clean cpp-build cpp-run
