alias r := rust

_default:
    @just --choose -f {{ justfile() }} -d  {{ invocation_directory() }}

rust:
    @just --choose -f $MY_SCRIPTS/rust.just -d {{ invocation_directory() }}

edit:
    @just --choose -f $MY_SCRIPTS/edit.just -d {{ invocation_directory() }}

cpp-build:
    g++ -ggdb3 -pthread main.cpp

cpp-run:
    ./a.out

cpp-clean:
    /bin/rm -rf a.out

cpp-build-run: cpp-clean cpp-build cpp-run

mise-install-java:
    mise install "java@$(mise ls-remote java | fzf)"

mise-global-java:
    mise use --global "java@$(mise ls-remote java | fzf)"
