[mgr]
show_hidden = true
sort_by = "mtime"
sort_dir_first = false
sort_reverse = true
linemode = "mtime"
# _v4_suppress_deprecation_warnings = true
ratio = [1, 2, 5]

# [[plugin.prepend_fetchers]]
# id = "git"
# name = "*"
# run = "git"
# 
# [[plugin.prepend_fetchers]]
# id = "git"
# name = "*/"
# run = "git"

[plugin]
prepend_previewers = [
    { name = "*.csv", run = "duckdb" },
    { name = "*.tsv", run = "duckdb" },
    { name = "*.json", run = "duckdb" },
    { name = "*.parquet", run = "duckdb" },
]

prepend_preloaders = [
    { name = "*.csv", run = "duckdb", multi = false },
    { name = "*.tsv", run = "duckdb", multi = false },
    { name = "*.json", run = "duckdb", multi = false },
    { name = "*.parquet", run = "duckdb", multi = false },
    { name = "*.db", run = "duckdb" },
    { name = "*.duckdb", run = "duckdb" },
]
