[manager]
show_hidden = true
sort_by = "mtime"
sort_dir_first = false
sort_reverse = true
linemode = "mtime"
_v4_suppress_deprecation_warnings = true
ratio = [1, 2, 5]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"
